### ISSUE TITLE
Example "Article" from JATS Samples not working

### ISSUE THREAD

**Issue by jorgesallum** [beijaflor-io/jats2tex#20]
I've just tried to run this example unsuccessfully. The LaTeX output is not that exactly. Please have a look

<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>

**Comment by yamadapc** [comment]
O consumo de memória estava muito alto, consertado na versão `0.9.2.0` junto com outras soluções de performance, indo para o ar.
