### ISSUE TITLE
images

### ISSUE THREAD

**Issue by yamadapc** [beijaflor-io/jats2tex#3]
read attributes from images and compile to figures

**Comment by yamadapc** [comment]
![screen shot 2017-07-20 at 1 30 44 pm](https://user-images.githubusercontent.com/3923654/28428392-abf09294-6d4f-11e7-99b8-982415c10b60.png)

`make example-images` to test, won't be supported on the web version preview.

**Comment by yamadapc** [comment]
@jorgesallum @aline-cristina @carolinatanigushi

LaTeX não suporta imagens TIF; há um jeito de realizar conversão automática que não será implementado. O XML deve referenciar formatos de imagem suportados pelo LaTeX.

**Comment by aline-cristina** [comment]
@yamadapc 

Ok. Ciente. 
[eu e a @carolinatanigushi testamos há pouco com o pacote graphicx e realmente não conseguimos fazer funcionar -- de qualquer forma, não publicamos tiff no site da SciELO, apesar de aceitarmos imagens nesse formato, na hora da conversão sempre serão publicadas imagens em formato web]
