### ISSUE TITLE
Accept full Xpath for for parenthood

### ISSUE THREAD

**Issue by jorgesallum** [beijaflor-io/jats2tex#34]
/One/Two/Three/Four

yaml

```
//Example:
One//Example:
One/Two/Example:
One/Two/Example[@example]:
One/Two/Example[@example="example"]:
```

**Comment by jorgesallum** [comment]
@yamadapc quanto tempo V estima para desenvolver isso? Talvez valha já fazer na primeira etapa do SPSTeX pois ajudaria muito os trabalhos de definição dos templates.

**Comment by jorgesallum** [comment]
@yamadapc vc acha que evolui com isso?

**Comment by yamadapc** [comment]
Vai dar bastante trabalho.. Tem uma issue descrevendo um pouco mais tecnicamente https://github.com/beijaflor-io/jats2tex/issues/30

Precisa implementar isso; vou tentar começar pra entender melhor

**Comment by yamadapc** [comment]
Tem algo que não está sendo possível de fazer de outro jeito?

**Comment by yamadapc** [comment]
Duplicado da #30
